# general settings for the bot
general:
    # version of the bot
    version: 2.6
    # prefixes for bot commands such as "X trivia", where X is one of the keys specified below
    prefix: ["lotr ","Lotr ","LOTR "]
    # python command to return the valid path for the cache folder
    cache_path: {'linux':'$HOME/.config/discord/bots/lotr-bot/',
                 'win32':'$appdata\discord\bots\lotr-bot\'}
    # logfile location (in cache directory)
    logfile: dcbot.log
    # autosave interval in seconds
    autosave: 300
    # user id of the developer
    developer_id: 277083306087022592
    # github-repo link
    github_repo: https://github.com/LinuxlasGNUleaf/LotR-TriviaBot

# settings for the reddit API used for pulling memes and stuff
reddit:
    # token file for authentication of the bot (located in general/cache_path)
    token: 'reddit.tk'
    # useragent string for authenticating
    useragent: 'post fetcher by /u/LotR-Fan42'
    # list of subreddits to pull posts from
    subreddits: ["lotrmemes","Hobbit_Memes"]
    # cache file for the list of pulled posts (located in general/cache_path)
    cache: meme_log.pyobj
    # interval in minutes before the pulled posts are considered outdated and are refetched
    refresh_interval: 300
    # number of posts to pull when pulling new posts, if all the pulled posts were already used, this number is doubled/tripled/etc. until a new post is found
    query_limit: 50
    # video thumbnail url for video posts
    video_thumbnail: https://cdn.onlinewebfonts.com/svg/download_349409.png

# settings for the youtube data API for searching for YT videos
youtube:
    # channel id for video search
    channel_id: UCYXpatz5Z4ek0M_5VR-Qt1A
    # number of search results to display
    max_video_count: 3
    # token file for the authentication (located in general/cache_path)
    token: google.tk
    # blacklist to remove obsolete lines from description 
    desc_blacklist: [teh lurd of teh reings youtube channel, media, shop, facebook.com,
                     instagram.com, music used, ‚ô´, just a facebook page, pardun us,
                     for ur, donation, discord, we post, like, follow, luminous,
                     outro, sub, sale, bit.ly, playlist, editor, channel]

# settings for google search API
google:
    # "site:"-argument to use in google search 
    site: tolkiengateway.net

# settings for the discord bot, all the DC-related minigames and configs
discord:
    # token file for authentication of the bot (located in general/cache_path)
    token: discord.tk

    # emojis for visual indicators
    indicators: [':x:',':white_check_mark:']
    # settings for the bot
    settings:
        # cache file for storing the settings specified for different servers (located in general/cache_path)
        cache: dc_settings.pyobj
        # help message displayed when working with the settings command
        help: |
            **How the settings work:**
            You can use the settings command in cases where you want to enable / disable specific categories.
            *Please note: If you want to completely turn off the bot in some parts of your server, use Channel Settings
            to disallow the bot to prevent the bot from sending messages there.*
            
            You can set preferences for a server or a channel (DMs excluded), which means you set the category to on / off.
            If set, the *channel preference* for a category will __always__ be preferred.
            If the *channel preference* for this category is not set, the server-preference will be used.
            If the *server preference* is not set either, the hardcoded fallback values are used.
            Refer to the attached image for further clarification. 


            **How to use the config command:**
            Syntax: `{0}setting [channel/server] [category] [on/off/reset]`
            - *First argument*: Edit channel-wide or server-wide settings?

            - *Second argument*: Which category do you want to edit?
            These are the categories that are available:
            {1}

            - *Third argument*: What mode do you want the setting to have?
            These are the modes that are available:
            `on`,`off`,`reset`
            Note: `reset` deletes the server/channel-preference, which makes the bot fall back to the next layer (see attached image) 

        # list of config categories (for internal use only, don't edit)
        categories:
            - autoscript
            - memes
            - minigames
            - lore
            - battles
        
        # fallback permissions, used when no relevant config is set at all
        defaults: {autoscript: 1, memes: 1, minigames: 1, lore: 1, battles: 0}
    
    # silmarillion quote settings
    silmarillion:
        # file containing the Silmarillion
        file: silmarillion.txt
        # number of sentences to be displayed
        sentence_count: 2
    
    # time for all participants of a battle to check in
    ready_check_timeout: 180

    # trivia battle settings
    trivia_battle:
        # time limit in which both of the participants have to answer (in seconds)
        timeout: 45

    # quote battle settings
    quote_battle:
        # time limit for the other participant to respond
        timeout: 300
        # number of rounds for quote battle
        rounds: 8
        # voting time for non-participants
        voting_time: 3600
        # dict of roles to ping for voting, format is: {server_id: role_id, server_id2: role_id2, ...}
        voting_roles: {566219783377518592: 854003662891647006, 333978604763348993: 854006900042498078}

    # trivia game settings
    trivia:
        # determines the timeout duration (X characters per second)
        multiplier: 12
        # extra-time added to the timeout (in seconds) without regard of the length of the question
        extra_time: 5.0
        # marker used to mark correct answer
        marker: '*'
        # cache file for storing the trivia scoreboard (located in general/cache_path)
        cache: scoreboard.pyobj
        # link to trivia form to submit new questions
        link: https://forms.gle/k4oMTiyUEJgntMyb9
        # tips added when the link is displayed
        tips:
            - "U shel submit ur questions here: {}"
            - "Thought of a cool new trivia question? Great! Submit it here: {}"
            - "Are these questions 2 ez 4 u? Submit new ones here: {}"
            - "Are you versed in the ways of Middle Earth trivia? And if that is the case, would you mind sharing it? Submit new questions here: {}"
        # Double quotes ("") are important here, otherwise the escape sequence \n is not recognized
        medals: ["ü•á __Eru Il√∫vatar:__ \n{}", "ü•à __Manw√´:__\n{}", "ü•â __Galadriel:__\n{}\n", "{}"]

        scoreboard_line: '**[{} pts / {}%]** {}'
        scoreboard_streak: ' :dart: *Streak of {} wins*'
        # probability to display the link and a tip
        tip_probability: 0.05
        # top X players to show on the scoreboard
        scoreboard_max: 25
        # minimum number of players in a server necessary to create a graphical scoreboard
        gscoreboard_min: 10 
        # maximum number of players to display on the graphical scoreboard
        gscoreboard_max: 15
        # file for storing anonymous statistics about the trivia games (located in general/cache_path)
        stats_cache: 'questions_stats.txt'
    
    # hangman game settings
    hangman:
        # time limit for each guess
        timeout: 20
        # ascii-art for the hangman game 
        ongoing_states:
            - "``` \n \n \n \n \nililililillllililii```"
            - "```    //\n    ||\n    ||\n    ||\n    ||    \nililililillllililii```"
            - "```    //====\\\n    ||\n    ||\n    ||\n    ||\n    ||\nililililillllililii```"
            - "```    //====\\\n    ||    |\n    ||   (\")\n    ||\n    ||\n    ||\nililililillllililii```"
            - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|\n    ||\n    ||\nililililillllililii```"
            - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||\n    ||\n    ||\nililililillllililii```"
            - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   /\n    ||\nililililillllililii```"
        end_states:
            - "```    //====\\\n    ||    |\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\n    ||\nililililillllililii```"
            - "```    //====\\\n    ||\n    ||\n    ||   (\")\n    ||   \\|/\n    ||    X\n    ||   / \\\nililililillllililii```"

    # autoscript settings
    autoscript:
        # script file for autoscript
        file: script.txt
        # determines whether the autoscript should stop at the end of a scene
        scene_end_interrupt: False
        # settings for the condensed script (for internal use only)
        punctuation_chars: ['?','!','.',':',';']
        elimination_chars: ["'",","]
        # threshold for the SequenceMatcher a message has to meet to be accepted as a quote input
        threshold: 0.85 
        # number of lines of the script that will be outputted
        dialog_count: 2

    autogimli:
        # interval in which autogimli will be triggered
        interval: [2,100000]
        # chance an autogimli event will happen (1 in x, 1/x)
        chance: 100
        # cooldown in seconds before autogimli will react to the same user again
        cooldown: 300
        # custom emojis to react with on messages, server-specific
        special_reactions: {566219783377518592 : '<:Gumli:596753586147426355>'}
        # whether or not a special message is displayed if the number 2 (two) is detected
        number_two_special_message: True


    autorepost:
        # match threshold for the repost msg to trigger
        threshold: 0.91
        # servers where this function will be active
        servers: [566219783377518592, 333978604763348993]
        # reactions to add to the message
        reactions: ['‚õî','üö®','ü§°','‚ôªÔ∏è']
        # trigger words to look for
        trigger_words:
            - repost
            - reposting
            - reposted
        # cooldown in seconds before autorepost will react to the same user again
        cooldown: 300
        # messages to add to the embed
        message:
            - ü§ñ Beep. Boop. repost detected, opinion rejected.
            - Yep. Pretty sure I used to know a guy that said he saw a Facebook post that linked to a YouTube comment referencing a guy's post on Tumblr who talked about this guy's teacher's cousin's sister's daughter's dog's roommate's dentist's cousin's step brother who knows a guy who knows a guy who knows a guy who knows a guy who knows this guy's cousin that once posted that EXACT thing on a forum that got taken down in 2009 therefore making it a repost. I'll bring the pitchforks if someone else brings the torches let's get op and burn him at the stake.
            - Never apologize to repost police. Thousands of people have never seen this before. Many of us do not live on reddit day in and day out. Reddit is not a static environment. Repost police exist to suck the joy out of OPs and whine about having to scroll for an extra seven milliseconds.
            - I've finally figured it out. The world is slowly getting worse, and this... thing that you just reposted proves it. According to even the bible itself, the world will grow worse and worse and you're living proof of that. I was a staunch atheist all my life. I attended atheist megachurches, converted over 300 Christians to atheism, and currently have an outstanding IQ of over 150. I studied every bible and bible type book ever and they all seemed ridiculous and debunk able. I've even converted people with a doctorate in ministry. But what you just copied is so bad it proved to me that Satan exists. And I just had a thought; if Satan exists, God must, too. Your absolute mistake against humanity is so much so that it proves the existence of God, and even I'm wondering how we ended up in this place. How did God create you in this way? Or were you a creation of Satan? Or maybe you're a demon who somehow found a way onto a computer with the sole intention of spreading evil around the world to corrupt it. Honestly I have no idea. Whatever you are, I am personally going to attend church for the first time and beg God to protect me from the evil you have plagued my mind with and hopefully either exorcise the demon out of you or, if you really are a demon, exorcise you in general. Have a rotten day.
        # authors of the embed
        author:
            - General Reposti
            - Darth Stealious
            - Zero effort the Hutt
            - Jango Theft
            - Commander Copy
            - Reposter Rex
            - Darth Plagiarism the Unwise
            - Clone Trooper
            - Duplikit fisto
            - Ki Fraudi Mundi
            - Master Stealfo dyas
            - Anakin Stealwalker
            - Count Twoku
            - Master Olda
            - Grabba The Hutt
            - Viceroy Not Again Ray
            - Thieve Palpatine
        author_pfp:
            - 'https://wiki.soyjak.party/images/d/df/SoyWojak_gape.png'
            - 'https://wiki.soyjak.party/images/thumb/d/d5/ETB_Soyjak.png/600px-ETB_Soyjak.png'
            - 'https://wiki.soyjak.party/index.php?title=File:SoyWojak_Gape.png'
        media:
            - 'https://c.tenor.com/jcxlwCGt5YwAAAAS/jurassic-park-repost.gif'
            - 'https://c.tenor.com/wziKCIFwyxcAAAAC/repost-running.gif'
            - 'https://c.tenor.com/YFyrK_pv48wAAAAS/doug-walker.gif'
            - 'https://i.kym-cdn.com/photos/images/newsfeed/002/173/133/6cc.png'


    #color codes for Embeds
    colors: {'WHITE': 0xFFFFFF,
             'AQUA': 0x1ABC9C,
             'GREEN': 0x2ECC71,
             'BLUE': 0x3498DB,
             'PURPLE': 0x9B59B6,
             'LUMINOUS_VIVID_PINK': 0xE91E63,
             'GOLD': 0xF1C40F,
             'ORANGE': 0xE67E22,
             'RED': 0xE74C3C,
             'NAVY': 0x34495E,
             'DARK_AQUA': 0x11806A,
             'DARK_GREEN': 0x1F8B4C,
             'DARK_BLUE': 0x206694,
             'DARK_PURPLE': 0x71368A,
             'DARK_VIVID_PINK': 0xAD1457,
             'DARK_GOLD': 0xC27C0E,
             'DARK_ORANGE': 0xA84300,
             'DARK_RED': 0x992D22,
             'DARK_NAVY': 0x2C3E50}
    
    # status messages for the bot
    status:
        - Boromir not simply walk into Mordor
        - Viggo Mortensen break his toe
        - Gimli lose his shoe
        - Legolas no-scoping Orcs
        - Merry and Pippin smoking pipe-weed
        - Eowyn brewing a stew
        - Gandalf bumping his head in Bag End
        - Feanor doing nothing wrong
        - Frodo getting stabbed by Shelob
        - Smeagol smacc Sam with a stone
        - Aragorn charging for Frodo
        - Tom Bombadil singing and stomping through the Old Forest

    # insults for failed trivia games or invalid queries
    insults:
        - "Stupid fat {}!"
        - "Fool of a {}! Stay quiet next time and rid us of your stupidity!"
        - "I would cut off your head {}... if it stood but a little higher from the ground."
        - "Dotard! What is the house of {} but a thatched barn where brigands drink in the reek,and their brats roll on the floor among the dogs?"
        - "Hey, {}! Don't go getting too far behind. ~Sam"
        - "Feanor did nothing wrong, but the same can not be said about you, {}!"
        - "Bombur does not approve."
        - "Stop your squeaking you dunghill rat, {}!"
        - "You stinking two-faced sneak!"
        - "The wise speak only of what they know, {}. A witless worm have you become. Therefore be silent, and keep your forked tongue behind your teeth!s"

    # compliments for won trivia games
    compliments:
        - "Well done, my dear {}!"
        - "{}, you should be counted amongst the wise of Middle Earth."
        - "Very good {}, I could not have done it better myself!"
        - "Bombur approves. Well done, {}!"
        - "May the wind under your wings bear you where the sun sails and the moon walks."
        - "May the stars shine upon your face!"
        - "May your beer be laid under an enchantment of surpassing excellence for seven years!"
